<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $coffeeCategory = Category::where('slug', 'coffee')->first();
        $nonCoffeeCategory = Category::where('slug', 'non-coffee')->first();
        $foodCategory = Category::where('slug', 'food')->first();
        $snackCategory = Category::where('slug', 'snack')->first();
        $dessertCategory = Category::where('slug', 'dessert')->first();
        
        $products = [
            // Coffee Products
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Cappuccino',
                'slug' => 'cappuccino',
                'description' => 'The combination of coffee, milk, and palm sugar makes this drink delicious',
                'price' => 4.98,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Coffee Latte',
                'slug' => 'coffee-latte',
                'description' => 'This caffe latte or coffee latte is one of the popular types of milk coffee',
                'price' => 5.98,
                'image' => 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Americano',
                'slug' => 'americano',
                'description' => 'Americano coffee is espresso drinks combined with hot water',
                'price' => 5.98,
                'image' => 'https://images.unsplash.com/photo-1551030173-122aabc4489c?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Espresso',
                'slug' => 'espresso',
                'description' => 'Strong and bold espresso shot with rich crema',
                'price' => 4.50,
                'image' => 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Mocha',
                'slug' => 'mocha',
                'description' => 'Rich chocolate combined with espresso and steamed milk',
                'price' => 6.50,
                'image' => 'https://images.unsplash.com/photo-1607260550778-aa9d29444ce1?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'V60',
                'slug' => 'v60',
                'description' => 'The V60 technique is one of the most used techniques by barista',
                'price' => 5.98,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Iced Latte',
                'slug' => 'iced-latte',
                'description' => 'Refreshing iced coffee with creamy milk over ice',
                'price' => 5.50,
                'image' => 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Iced Americano',
                'slug' => 'iced-americano',
                'description' => 'Bold espresso poured over ice with cold water',
                'price' => 4.75,
                'image' => 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Caramel Macchiato',
                'slug' => 'caramel-macchiato',
                'description' => 'Espresso marked with vanilla syrup and caramel drizzle',
                'price' => 6.25,
                'image' => 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Flat White',
                'slug' => 'flat-white',
                'description' => 'Microfoam milk poured over a double shot of espresso',
                'price' => 5.75,
                'image' => 'https://images.unsplash.com/photo-1634016524565-c6eb1eb3b306?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],

            // Non-Coffee (Tea & Others)
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Green Tea',
                'slug' => 'green-tea',
                'description' => 'Fresh organic green tea with antioxidants',
                'price' => 3.50,
                'image' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Khmer Tea',
                'slug' => 'khmer-tea',
                'description' => 'Sweet and creamy Khmer-style tea',
                'price' => 4.50,
                'image' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Matcha Latte',
                'slug' => 'matcha-latte',
                'description' => 'Premium Japanese matcha with steamed milk',
                'price' => 5.50,
                'image' => 'https://images.unsplash.com/photo-1536013266805-f6c39e0e2dc5?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Chai Latte',
                'slug' => 'chai-latte',
                'description' => 'Spiced black tea with steamed milk and honey',
                'price' => 4.75,
                'image' => 'https://images.unsplash.com/photo-1578899952107-9d9d3b7c65b3?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Hot Chocolate',
                'slug' => 'hot-chocolate',
                'description' => 'Rich and creamy hot chocolate with marshmallows',
                'price' => 4.25,
                'image' => 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Lemon Tea',
                'slug' => 'lemon-tea',
                'description' => 'Refreshing black tea with fresh lemon',
                'price' => 3.75,
                'image' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],

            // Food
            [
                'category_id' => $foodCategory->id,
                'name' => 'Chicken Sandwich',
                'slug' => 'chicken-sandwich',
                'description' => 'Grilled chicken with fresh vegetables on artisan bread',
                'price' => 8.50,
                'image' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Club Sandwich',
                'slug' => 'club-sandwich',
                'description' => 'Triple-decker with turkey, bacon, lettuce and tomato',
                'price' => 9.75,
                'image' => 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Pasta Carbonara',
                'slug' => 'pasta-carbonara',
                'description' => 'Creamy pasta with bacon and parmesan cheese',
                'price' => 12.50,
                'image' => 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Caesar Salad',
                'slug' => 'caesar-salad',
                'description' => 'Fresh romaine lettuce with caesar dressing and croutons',
                'price' => 7.50,
                'image' => 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Breakfast Burrito',
                'slug' => 'breakfast-burrito',
                'description' => 'Scrambled eggs, cheese, and bacon wrapped in tortilla',
                'price' => 8.75,
                'image' => 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],

            // Snacks
            [
                'category_id' => $snackCategory->id,
                'name' => 'Croissant',
                'slug' => 'croissant',
                'description' => 'Buttery and flaky French pastry',
                'price' => 3.50,
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Chocolate Croissant',
                'slug' => 'chocolate-croissant',
                'description' => 'Croissant filled with rich chocolate',
                'price' => 4.25,
                'image' => 'https://images.unsplash.com/photo-1623334044303-241021148842?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Blueberry Muffin',
                'slug' => 'blueberry-muffin',
                'description' => 'Freshly baked muffin with juicy blueberries',
                'price' => 3.75,
                'image' => 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Banana Bread',
                'slug' => 'banana-bread',
                'description' => 'Moist and sweet homemade banana bread',
                'price' => 3.25,
                'image' => 'https://images.unsplash.com/photo-1606312619070-d48b4cbc8bf7?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Chocolate Chip Cookie',
                'slug' => 'chocolate-chip-cookie',
                'description' => 'Classic cookie loaded with chocolate chips',
                'price' => 2.50,
                'image' => 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Cinnamon Roll',
                'slug' => 'cinnamon-roll',
                'description' => 'Warm cinnamon roll with cream cheese frosting',
                'price' => 4.50,
                'image' => 'https://images.unsplash.com/photo-1626197031507-c17099753214?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Donut',
                'slug' => 'donut',
                'description' => 'Glazed donut with sweet icing',
                'price' => 2.75,
                'image' => 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Pretzel',
                'slug' => 'pretzel',
                'description' => 'Soft pretzel with sea salt',
                'price' => 3.25,
                'image' => 'https://images.unsplash.com/photo-1558326567-98ae2405596b?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $snackCategory->id,
                'name' => 'Scone',
                'slug' => 'scone',
                'description' => 'Buttermilk scone with berries',
                'price' => 3.75,
                'image' => 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],

            // Desserts
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Tiramisu',
                'slug' => 'tiramisu',
                'description' => 'Italian coffee-flavored dessert with mascarpone',
                'price' => 6.50,
                'image' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Cheesecake',
                'slug' => 'cheesecake',
                'description' => 'Creamy New York style cheesecake',
                'price' => 6.25,
                'image' => 'https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Chocolate Cake',
                'slug' => 'chocolate-cake',
                'description' => 'Rich and moist chocolate layer cake',
                'price' => 5.75,
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Strawberry Shortcake',
                'slug' => 'strawberry-shortcake',
                'description' => 'Light sponge cake with fresh strawberries and cream',
                'price' => 6.00,
                'image' => 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Apple Pie',
                'slug' => 'apple-pie',
                'description' => 'Classic apple pie with cinnamon and flaky crust',
                'price' => 5.50,
                'image' => 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Brownie',
                'slug' => 'brownie',
                'description' => 'Fudgy chocolate brownie with walnuts',
                'price' => 4.25,
                'image' => 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Red Velvet Cake',
                'slug' => 'red-velvet-cake',
                'description' => 'Classic red velvet with cream cheese frosting',
                'price' => 6.50,
                'image' => 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Carrot Cake',
                'slug' => 'carrot-cake',
                'description' => 'Spiced carrot cake with cream cheese frosting',
                'price' => 5.75,
                'image' => 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Lemon Tart',
                'slug' => 'lemon-tart',
                'description' => 'Tangy lemon curd in a buttery pastry shell',
                'price' => 5.25,
                'image' => 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $dessertCategory->id,
                'name' => 'Macarons',
                'slug' => 'macarons',
                'description' => 'French almond meringue cookies (3 pieces)',
                'price' => 5.50,
                'image' => 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],

            // More Coffee Items
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Affogato',
                'slug' => 'affogato',
                'description' => 'Vanilla ice cream drowned in hot espresso',
                'price' => 6.75,
                'image' => 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Cortado',
                'slug' => 'cortado',
                'description' => 'Equal parts espresso and steamed milk',
                'price' => 4.75,
                'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],
            [
                'category_id' => $coffeeCategory->id,
                'name' => 'Macchiato',
                'slug' => 'macchiato',
                'description' => 'Espresso marked with a dollop of foam',
                'price' => 4.50,
                'image' => 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
                'has_temperature' => true,
                'has_size' => true,
            ],

            // More Non-Coffee Items
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Iced Tea',
                'slug' => 'iced-tea',
                'description' => 'Refreshing iced black tea with lemon',
                'price' => 3.50,
                'image' => 'https://images.unsplash.com/photo-1499638309848-e9968540da83?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Smoothie',
                'slug' => 'smoothie',
                'description' => 'Mixed berry smoothie with yogurt',
                'price' => 5.75,
                'image' => 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],
            [
                'category_id' => $nonCoffeeCategory->id,
                'name' => 'Fresh Orange Juice',
                'slug' => 'fresh-orange-juice',
                'description' => 'Freshly squeezed orange juice',
                'price' => 4.25,
                'image' => 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
                'has_temperature' => false,
                'has_size' => true,
            ],

            // More Food Items
            [
                'category_id' => $foodCategory->id,
                'name' => 'Avocado Toast',
                'slug' => 'avocado-toast',
                'description' => 'Smashed avocado on sourdough with poached egg',
                'price' => 9.50,
                'image' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Bagel with Cream Cheese',
                'slug' => 'bagel-cream-cheese',
                'description' => 'Fresh bagel with cream cheese and smoked salmon',
                'price' => 7.75,
                'image' => 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Quiche',
                'slug' => 'quiche',
                'description' => 'Savory quiche with spinach and mushroom',
                'price' => 8.25,
                'image' => 'https://images.unsplash.com/photo-1611564852120-3fad6b056d88?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Panini',
                'slug' => 'panini',
                'description' => 'Grilled panini with ham, cheese and tomato',
                'price' => 8.50,
                'image' => 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
            [
                'category_id' => $foodCategory->id,
                'name' => 'Soup of the Day',
                'slug' => 'soup-of-the-day',
                'description' => 'Homemade soup served with bread',
                'price' => 6.50,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
                'has_temperature' => false,
                'has_size' => false,
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create($productData);
            // Attach toppings only to beverages
            if (in_array($product->category_id, [$coffeeCategory->id, $nonCoffeeCategory->id])) {
                $product->toppings()->attach([1, 2, 3, 4, 5, 6, 7]);
            }
        }
    }
}
